vmm: migration: gracefully notify receiver about failed migration
We never notified the receiver about failed live migrations. This always
caused the "socket error: failed to fill whole buffer" errors - which
were a symptom but never the root cause. Now, a migration failure causes
a much nicer behavior on the receiving side.

I've tested this during precopy with multiple connections and right
before the handover.

before

```
Error: ch-remote exited with the following chain of errors:
  0: http client error
  1: Server responded with InternalServerError
  2: Error from API
  3: Error receiving migration
  4: Socket error
  5: failed to fill whole buffer
```

after

```
Error: ch-remote exited with the following chain of errors:
  0: http client error
  1: Server responded with InternalServerError
  2: Error from API
  3: Error receiving migration
  4: Failed to complete migration for migratable component
  5: Migration was aborted by sender
```

On-behalf-of: SAP philipp.schuster@sap.com
Signed-off-by: Philipp Schuster <philipp.schuster@cyberus-technology.de>