build: Fix cargo audit
Bump rustls to resolve the following issue:

 Crate:     rustls
 Version:   0.23.44
 Title:     TLS 1.3 handshake messages incorrectly accepted across
            encryption level boundaries
 ID:        RUSTSEC-2026-0285
 Severity:  5.3 (medium)
 Solution:  Upgrade to >=0.23.45
 error: 1 vulnerability found!

Signed-off-by: Bo Chen <bchen@crusoe.ai>

(cherry picked from upstream commit
3a4501f58c819d8c6ca2bee3b74c08002dcfb58c)

Slight modification to the commit since we use the `aws-lc-rs` feature
of `rustls`.

On-behalf-of: SAP julian.schindel@sap.com
Co-authored-by: Bo Chen <bchen@crusoe.ai>
Signed-off-by: Julian Schindel <julian.schindel@cyberus-technology.de>