ch-remote: fix panic in send-migration
Not sure why exactly it panicked but this is a working fix.

Orignal error:
```
thread 'main' (66708) panicked at src/bin/ch-remote.rs:512:22:
Mismatch between definition and access of `connections`. Could not downcast to core::num::nonzero::NonZero<u32>, need to downcast to u32
```

Signed-off-by: Philipp Schuster <philipp.schuster@cyberus-technology.de>
On-behalf-of: SAP philipp.schuster@sap.com